@startuml arch-1

component "bid-service" as BIDS

database "bids" as BIDS_TOPIC

BIDS --> BIDS_TOPIC: stores bid\nevents

component "auction-service" as AUCTION

database "auction" as AUCTION_TOPIC

AUCTION --> AUCTION_TOPIC: store final\ndeals

BIDS_TOPIC -> AUCTION: updates bid\nevents

BIDS_TOPIC <- AUCTION: updates bid\nwith new state

component "product-service" as PRODUCT

database "products" as PRODUCT_TOPIC

PRODUCT --> PRODUCT_TOPIC: stores product\nevents

AUCTION -> PRODUCT_TOPIC: updates products\nwith new state

AUCTION <- PRODUCT_TOPIC: updates products\nevents

component "info-service" as INFO

BIDS_TOPIC --> INFO: updates\nbid events

PRODUCT_TOPIC ---> INFO: updates products\nevents

AUCTION_TOPIC --> INFO: updates final\ndeals events


@enduml
