@startuml arch-1

component "bid-service" as BIDS

database "bids" as BIDS_TOPIC

BIDS --> BIDS_TOPIC: stores bid\nevents

component "recipe-service" as RECIPE

database "recipe" as RECIPE_TOPIC

RECIPE --> RECIPE_TOPIC: store final\ndeals

BIDS_TOPIC -> RECIPE: updates bid\nevents

BIDS_TOPIC <- RECIPE: updates bid\nwith new state

component "product-service" as PRODUCT

database "products" as PRODUCT_TOPIC

PRODUCT --> PRODUCT_TOPIC: stores product\nevents

RECIPE -> PRODUCT_TOPIC: updates products\nwith new state

RECIPE <- PRODUCT_TOPIC: updates products\nevents

component "info-service" as INFO

BIDS_TOPIC --> INFO: updates\nbid events

PRODUCT_TOPIC ---> INFO: updates products\nevents

RECIPE_TOPIC --> INFO: updates final\ndeals events


@enduml
